//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubberduck.Resources.v3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RubberduckMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RubberduckMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rubberduck.Resources.v3.RubberduckMessages", typeof(RubberduckMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show this message again.
        /// </summary>
        public static string DoNotShowAgain {
            get {
                return ResourceManager.GetString("DoNotShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified workspace folder is not empty.  
        ///Are you sure you want to **overwrite an existing project**?.
        /// </summary>
        public static string Message_ConfirmOverwriteExistingWorkspace {
            get {
                return ResourceManager.GetString("Message_ConfirmOverwriteExistingWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string MessageActionButton_Accept {
            get {
                return ResourceManager.GetString("MessageActionButton_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MessageActionButton_Cancel {
            get {
                return ResourceManager.GetString("MessageActionButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MessageActionButton_Close {
            get {
                return ResourceManager.GetString("MessageActionButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MessageActionButton_Confirm {
            get {
                return ResourceManager.GetString("MessageActionButton_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait, no.
        /// </summary>
        public static string MessageActionButton_No {
            get {
                return ResourceManager.GetString("MessageActionButton_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, proceed.
        /// </summary>
        public static string MessageActionButton_Yes {
            get {
                return ResourceManager.GetString("MessageActionButton_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm overwrite existing workspace.
        /// </summary>
        public static string MessageTitle_ConfirmOverwriteExistingWorkspace {
            get {
                return ResourceManager.GetString("MessageTitle_ConfirmOverwriteExistingWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document has unsaved changes! What should we do?.
        /// </summary>
        public static string OnDocumentTabClosed {
            get {
                return ResourceManager.GetString("OnDocumentTabClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        public static string UnsavedChanges_Discard {
            get {
                return ResourceManager.GetString("UnsavedChanges_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UnsavedChanges_LeaveOpen {
            get {
                return ResourceManager.GetString("UnsavedChanges_LeaveOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save first.
        /// </summary>
        public static string UnsavedChanges_SaveAndClose {
            get {
                return ResourceManager.GetString("UnsavedChanges_SaveAndClose", resourceCulture);
            }
        }
    }
}
