//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubberduck.Resources.v3 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RubberduckUICommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RubberduckUICommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rubberduck.Resources.v3.RubberduckUICommands", typeof(RubberduckUICommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FileCommands_CloseActiveDocumentCommandText {
            get {
                return ResourceManager.GetString("FileCommands_CloseActiveDocumentCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all.
        /// </summary>
        public static string FileCommands_CloseAllDocumentsCommandText {
            get {
                return ResourceManager.GetString("FileCommands_CloseAllDocumentsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close project/workspace.
        /// </summary>
        public static string FileCommands_CloseProjectCommandText {
            get {
                return ResourceManager.GetString("FileCommands_CloseProjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string FileCommands_ExitCommandText {
            get {
                return ResourceManager.GetString("FileCommands_ExitCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New....
        /// </summary>
        public static string FileCommands_NewProjectCommandText {
            get {
                return ResourceManager.GetString("FileCommands_NewProjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder in Windows Explorer.
        /// </summary>
        public static string FileCommands_OpenFolderInWindowsExplorerCommandText {
            get {
                return ResourceManager.GetString("FileCommands_OpenFolderInWindowsExplorerCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string FileCommands_OpenProjectCommandText {
            get {
                return ResourceManager.GetString("FileCommands_OpenProjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename project/workspace....
        /// </summary>
        public static string FileCommands_RenameProjectCommandText {
            get {
                return ResourceManager.GetString("FileCommands_RenameProjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string FileCommands_SaveActiveDocumentAsCommandText {
            get {
                return ResourceManager.GetString("FileCommands_SaveActiveDocumentAsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FileCommands_SaveActiveDocumentCommandText {
            get {
                return ResourceManager.GetString("FileCommands_SaveActiveDocumentCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string FileCommands_SaveAllDocumentsCommandText {
            get {
                return ResourceManager.GetString("FileCommands_SaveAllDocumentsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as template....
        /// </summary>
        public static string FileCommands_SaveProjectAsTemplateCommandText {
            get {
                return ResourceManager.GetString("FileCommands_SaveProjectAsTemplateCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize project/workspace.
        /// </summary>
        public static string FileCommands_SynchronizeProjectCommandText {
            get {
                return ResourceManager.GetString("FileCommands_SynchronizeProjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear content.
        /// </summary>
        public static string ServerTraceCommands_ClearContentCommandText {
            get {
                return ResourceManager.GetString("ServerTraceCommands_ClearContentCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ServerTraceCommands_CopyContentCommandText {
            get {
                return ResourceManager.GetString("ServerTraceCommands_CopyContentCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View server logs.
        /// </summary>
        public static string ServerTraceCommands_OpenLogFileCommandText {
            get {
                return ResourceManager.GetString("ServerTraceCommands_OpenLogFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause/resume trace.
        /// </summary>
        public static string ServerTraceCommands_PauseTraceCommandText {
            get {
                return ResourceManager.GetString("ServerTraceCommands_PauseTraceCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown server.
        /// </summary>
        public static string ServerTraceCommands_ShutdownServerCommandText {
            get {
                return ResourceManager.GetString("ServerTraceCommands_ShutdownServerCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file....
        /// </summary>
        public static string WorkspaceExplorerCommands_CreateFileCommandText {
            get {
                return ResourceManager.GetString("WorkspaceExplorerCommands_CreateFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        public static string WorkspaceExplorerCommands_CreateFolderCommandText {
            get {
                return ResourceManager.GetString("WorkspaceExplorerCommands_CreateFolderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string WorkspaceExplorerCommands_DeleteUriCommandText {
            get {
                return ResourceManager.GetString("WorkspaceExplorerCommands_DeleteUriCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string WorkspaceExplorerCommands_OpenFileCommandText {
            get {
                return ResourceManager.GetString("WorkspaceExplorerCommands_OpenFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string WorkspaceExplorerCommands_RenameUriCommandText {
            get {
                return ResourceManager.GetString("WorkspaceExplorerCommands_RenameUriCommandText", resourceCulture);
            }
        }
    }
}
