using Rubberduck.RPC.Proxy.SharedServices.Abstract;
using Rubberduck.RPC.Proxy.SharedServices.Server.Configuration;

namespace Rubberduck.RPC.Proxy.SharedServices.Server.Abstract
{
    /// <summary>
    /// The base interface for a RSP/LSP server proxy.
    /// </summary>
    /// <typeparam name="TOptions">The class type for the configuration options of this server.</typeparam>
    /// <typeparam name="TClientProxy">The interface type for the client proxy generated by StreamJsonRpc on the server side.</typeparam>
    /// <remarks>
    /// This interface must be implemented on the server side.
    /// Proxy implementations should be stateless: the instance only lives for the duration of a single request.
    /// </remarks>
    public interface IConfigurableServerProxy<TOptions, TClientProxy, TCommands> : IConfigurableProxy<TOptions>
        where TOptions : SharedServerCapabilities, new()
        where TClientProxy : class
        where TCommands : class
    {
        /// <summary>
        /// Gets a client proxy exposing client-to-server notifications.
        /// </summary>
        TClientProxy ClientProxy { get; }

        /// <summary>
        /// Gets a service that reeturns the current server state.
        /// </summary>
        IServerStateService<TOptions> ServerStateService { get; }

        /// <summary>
        /// Gets the server's console logger.
        /// </summary>
        IServerLogger Logger { get; }

        /// <summary>
        /// Gets the commands that handle the server-level requests and notifications sent or received by this server.
        /// </summary>
        TCommands Commands { get; }
    }
}