using Rubberduck.RPC.Platform;
using Rubberduck.RPC.Proxy.SharedServices.Server.Configuration;

namespace Rubberduck.RPC.Proxy.SharedServices.Abstract
{
    /// <summary>
    /// The base interface for a RSP/LSP server proxy.
    /// </summary>
    /// <typeparam name="TOptions">The class type for the configuration options of this server.</typeparam>
    /// <typeparam name="TClientProxy">The interface type for the client proxy generated by StreamJsonRpc on the server side.</typeparam>
    /// <remarks>
    /// This interface must be implemented on the server side.
    /// Proxy implementations should be stateless: the instance only lives for the duration of a single request.
    /// </remarks>
    public interface IConfigurableServerProxy<TOptions, TClientProxy> : IConfigurableProxy<TOptions>
        where TOptions : SharedServerCapabilities, new()
        where TClientProxy : class
    {
        /// <summary>
        /// Represents the client-side RPC proxy.
        /// </summary>
        /// <remarks>
        /// Fires events for client-to-server notifications. Invoked methods run client-side.
        /// </remarks>
        TClientProxy ClientProxy { get; }
    }

    /// <summary>
    /// The base interface for a configurable RPC proxy.
    /// </summary>
    /// <typeparam name="TOptions">The class type for the configuration options for this proxy.</typeparam>
    /// <remarks>
    /// Proxy implementations should be stateless: the instance only lives for the duration of a single request.
    /// </remarks>
    public interface IConfigurableProxy<TOptions> : IJsonRpcTarget
        where TOptions : class, new()
    {
        /// <summary>
        /// Configuration options for this server.
        /// </summary>
        TOptions Configuration { get; }
    }
}