VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "SomeService"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@ModuleDescription "A service that does something with a FeatureModel."
Option Explicit

'@Description "Does something."
Public Sub DoSomething(ByVal Model As FeatureModel)
    ' TODO something
End Sub
